condense_wildcard_suffixes = true
match_block_trailing_comma = true
merge_imports = true
report_fixme = "Unnumbered"
report_todo = "Unnumbered"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 120
