language: rust
rust:
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo 'clippy already installed'
  - cargo install diesel_cli
script:
  - cargo fmt -- --write-mode=diff
  - cargo clippy --verbose
  - cargo test --verbose
matrix:
  include:
    - rust: nightly-2018-03-15
      env: # updating this will cause cache invalidation
        - CLIPPY_VERSION=0.0.190
notifications:
  on_failure: change
  on_success: change
