language: rust
rust:
  - nightly
cache: cargo
before_script:
  - rustup component add rustfmt-preview
  - cargo install clippy --version $CLIPPY_VERSION || echo 'clippy already installed'
  - cargo install cargo-tarpaulin
  - cargo install diesel_cli
script:
  - cargo fmt -- --write-mode=diff
  - cargo clippy --verbose
  - cargo test --verbose
after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
matrix:
  include:
    - rust: nightly-2018-04-14
      env: # updating this will cause cache invalidation
        - CLIPPY_VERSION=0.0.194
notifications:
  on_failure: change
  on_success: change
