openapi: '3.0'
info:
  title: Apertium Stats Service
  version: '0.1.0'
  description: Stateful Rust web service that enables the efficient concurrent compilation
    and distribution of statistics regarding Apertium packages via a RESTful API.
servers:
  - url: http://localhost:8000
    description: Development
paths:
  /:
    get:
      summary: Returns usage instructions
      responses:
        '200':
            description: Usage instructions
            content:
              text/plain: {}
  /{package}:
    parameters:
      - $ref: '#/components/parameters/Package'
      - $ref: '#/components/parameters/Recursive'
      - $ref: '#/components/parameters/Async'
    get:
      summary: Returns statistics for the specified package
      responses:
        '200':
          $ref: '#components/responses/Stats'
        '202':
          $ref: '#components/responses/StatsInProgress'
        '429':
          $ref: '#components/responses/StatsAlreadyInProgress'
        '400':
          $ref: '#components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/PackageNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Computes statistics for the specified package
      responses:
        '202':
          $ref: '#components/responses/StatsInProgress'
        '429':
          $ref: '#components/responses/StatsAlreadyInProgress'
        '400':
          $ref: '#components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /{package}/{kind}:
    parameters:
      - $ref: '#/components/parameters/Package'
      - $ref: '#/components/parameters/Kind'
      - $ref: '#/components/parameters/Recursive'
      - $ref: '#/components/parameters/Async'
    get:
      summary: Returns statistics of the specified kind for the specified package
      responses:
        '200':
          $ref: '#components/responses/Stats'
        '202':
          $ref: '#components/responses/StatsInProgress'
        '429':
          $ref: '#components/responses/StatsAlreadyInProgress'
        '400':
          $ref: '#components/responses/BadRequestError'
        '404':
          $ref: '#/components/responses/PackageNotFoundError'
        '500':
          $ref: '#/components/responses/InternalServerError'
    post:
      summary: Computes statistics of the specified kind for the specified package
      responses:
        '202':
          $ref: '#components/responses/StatsInProgress'
        '429':
          $ref: '#components/responses/StatsAlreadyInProgress'
        '400':
          $ref: '#components/responses/BadRequestError'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  responses:
    Stats:
      description: Package statistics
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              stats:
                $ref: '#/components/schemas/Stats'
              in_progress:
                $ref: '#/components/schemas/StatsInProgress'
    StatsInProgress:
      description: Package statistics in progress
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                example: apertium-pl-dsb
                type: string
              in_progress:
                $ref: '#/components/schemas/StatsInProgress'
    StatsAlreadyInProgress:
      description: Package statistics already in progress
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                example: apertium-pl-dsb
                type: string
              in_progress:
                $ref: '#/components/schemas/StatsInProgress'
    BadRequestError:
      description: Bad request error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    PackageNotFoundError:
      description: Package not found error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: Internal server error
  parameters:
    Package:
      name: package
      in: path
      required: true
      description: package identifier
      example: apertium-pl-dsb
      schema:
        type: string
    Kind:
      name: kind
      in: kind
      required: true
      description: file kind identifier
      example: bidix
      schema:
        type: string
    Recursive:
      name: recursive
      in: query
      description: whether file search should be recursive
      schema:
        type: boolean
        default: false
    Async:
      name: async
      in: query
      description: whether statistics compilation should be asynchronous
      schema:
        type: boolean
        default: true
  schemas:
    Error:
      type: object
      properties:
        name:
          example: apertium-pl-dsb
          type: string
        error:
          example: No recognized files
          type: string
    StatKind:
      type: string
      enum:
        - Entries
        - Paradigms
        - Rules
        - Macros
        - Stems
        - VanillaStems
    FileKind:
      type: string
      enum:
        - Monodix
        - Bidix
        - MetaMonodix
        - MetaBidix
        - Postdix
        - Rlx
        - Transfer
        - Lexc
        - Twol
    File:
      type: object
      properties:
        last_author:
          type: string
          example: jim.o.regan
        size:
          type: integer
          example: 13
        last_changed:
          type: string
          format: date-time
        path:
          type: string
          example: apertium-pl-dsb.pl-dsb.dix
        revision:
          type: integer
          example: 13
    Stats:
      type: array
      items:
        allOf:
          - $ref: '#/components/schemas/File'
          - type: object
            properties:
              name:
                type: string
                example: apertium-pl-dsb
              file_kind:
                $ref: '#components/schemas/FileKind'
                example: stems
              stat_kind:
                $ref: '#components/schemas/StatKind'
                example: rlx
              value:
                example: 366
              created:
                type: string
                format: date-time
              requested:
                type: string
                format: date-time
    StatsInProgress:
      type: array
      items:
        type: object
        properties:
          file:
            $ref: '#/components/schemas/File'
          kind:
            $ref: '#components/schemas/FileKind'
          created:
            type: string
            format: date-time
